---@class DKEnchantAbbr
---@field Razorice string
---@field Sanguination string
---@field Spellwarding string
---@field Apocalypse string
---@field FallenCrusader string
---@field StoneskinGargoyle string
---@field UnendingThirst string

---@class TextReplacement
---@field original string
---@field replacement string

---@alias CharacterSlot CharacterHeadSlot|CharacterNeckSlot|CharacterShoulderSlot|CharacterBackSlot|CharacterChestSlot|CharacterShirtSlot|CharacterTabardSlot|CharacterWristSlot|CharacterHandsSlot|CharacterWaistSlot|CharacterLegsSlot|CharacterFeetSlot|CharacterFinger0Slot|CharacterFinger1Slot|CharacterTrinket0Slot|CharacterTrinket1Slot|CharacterMainHandSlot|CharacterSecondaryHandSlot

---@alias InspectSlotName "InspectHeadSlot"|"InspectNeckSlot"|"InspectShoulderSlot"|"InspectBackSlot"|"InspectChestSlot"|"InspectShirtSlot"|"InspectTabardSlot"|"InspectWristSlot"|"InspectHandsSlot"|"InspectWaistSlot"|"InspectLegsSlot"|"InspectFeetSlot"|"InspectFinger0Slot"|"InspectFinger1Slot"|"InspectTrinket0Slot"|"InspectTrinket1Slot"|"InspectMainHandSlot"|"InspectSecondaryHandSlot"

---@class ItemSlot: Button
---@field IsLeftSide boolean?
---@field PGVCharSlot PGVCharSlotMixin
---@field PGVInspectSlot PGVInspectSlotMixin

---@class CharacterStatFrame: Frame
---@field Label FontString
---@field Value FontString
---@field Background Texture
---@field numericValue number

---@class InspectInfo
---@field slots InspectSlotName[]
---@field leftSideSlots InspectSlotName[]
---@field bottomSlots InspectSlotName[]

---@class ExpansionDetails
---@field NameAbbr string
---@field LevelCap number
---@field SocketableSlots (CharacterSlot|InspectSlotName)[]
---@field AuxSocketableSlots (CharacterSlot|InspectSlotName)[]
---@field MaxSocketsPerItem number
---@field MaxAuxSocketsPerItem number
---@field MaxEmbellishments number
---@field EnchantableSlots (CharacterSlot|InspectSlotName)[]
---@field ShieldEnchantAvailable boolean
---@field OffhandEnchantAvailable boolean

---@alias RaceIcon { Male: string, Female: string }
---@class RaceIcons
---@field Human RaceIcon
---@field Dwarf RaceIcon
---@field NightElf RaceIcon
---@field Gnome RaceIcon
---@field Draenei RaceIcon
---@field Worgen RaceIcon
---@field VoidElf RaceIcon
---@field LightforgedDraenei RaceIcon
---@field DarkIronDwarf RaceIcon
---@field KulTiran RaceIcon
---@field Mechagnome RaceIcon
---@field Orc RaceIcon
---@field Undead RaceIcon
---@field Tauren RaceIcon
---@field Troll RaceIcon
---@field BloodElf RaceIcon
---@field Goblin RaceIcon
---@field Nightborne RaceIcon
---@field HighmountainTauren RaceIcon
---@field MagharOrc RaceIcon
---@field ZandalariTroll RaceIcon
---@field Vulpera RaceIcon
---@field Pandaren RaceIcon
---@field Dracthyr RaceIcon
---@field Earthen RaceIcon
---@field Haranir RaceIcon

---@class ClassIcons
---@field DeathKnight string
---@field DemonHunter string
---@field Druid string
---@field Evoker string
---@field Hunter string
---@field Mage string
---@field Monk string
---@field Paladin string
---@field Priest string
---@field Rogue string
---@field Shaman string
---@field Warlock string
---@field Warrior string

---@class HexColorPresets
---@field Poor string
---@field Uncommon string
---@field Rare string
---@field Epic string
---@field Legendary string
---@field Artifact string
---@field Heirloom string
---@field Info string
---@field PrevSeasonGear string
---@field Error string
---@field DeathKnight string
---@field DemonHunter string
---@field Druid string
---@field Evoker string
---@field Hunter string
---@field Mage string
---@field Monk string
---@field Paladin string
---@field Priest string
---@field Rogue string
---@field Shaman string
---@field Warlock string
---@field Warrior string

---@class Credit
---@field name string
---@field race? string
---@field class? string
---@field color string

---@class OutlineOption
---@field key string
---@field value string

---@class PGVSlotMixinBase: Frame
---@field ItemLevel FontString
---@field UpgradeTrack FontString
---@field Gems FontString
---@field Enchant FontString
---@field Embellishment Texture
---@field EmbellishmentShadow Texture
---@field IsLeftSideSlot boolean
---@field IsBottomSlot boolean

---@class PGVCharSlotMixin: PGVSlotMixinBase
---@field Durability FontString
---@field DurabilityBar StatusBar
---@field DurabilityBarBg StatusBar

---@class PGVInspectSlotMixin: PGVSlotMixinBase

---@class PGVToggleEnchantButton: Button
---@field tooltipText string
---@field UpdateTooltip fun(self: PGVToggleEnchantButton)
---@field UpdateTooltipText fun(self: PGVToggleEnchantButton, text: string)

---@class InspectPaperDollItemsFrame
---@field PGVAverageItemLevel FontString?

---@class TooltipDataLine
---@field gemIcon? number
---@field socketType? string

---@class PGVDatabaseProfileItemLevel
---@field show boolean
---@field scale number
---@field outline string
---@field onItem boolean
---@field useQualityColor boolean
---@field useClassColor boolean
---@field useGradientColors boolean
---@field useCustomColor boolean
---@field customColor string

---@class PGVDatabaseProfileUpgradeTrack
---@field show boolean
---@field scale number
---@field outline string
---@field useQualityScaleColors boolean
---@field useCustomColor boolean
---@field customColor string

---@class PGVDatabaseProfileGems
---@field show boolean
---@field scale number
---@field showMissing boolean
---@field missingMaxLevelOnly boolean

---@class PGVDatabaseProfileEnchants
---@field show boolean
---@field scale number
---@field outline string
---@field showMissing boolean
---@field missingMaxLevelOnly boolean
---@field collapse boolean
---@field showTextButton boolean
---@field useCustomColor boolean
---@field customColor string

---@class PGVDatabaseProfileDurability
---@field show boolean
---@field scale number
---@field showAsBar boolean
---@field colorHigh string
---@field colorMedium string
---@field colorLow string

---@class PGVDatabaseProfileInspect
---@field show boolean
---@field showAvgILvl boolean
---@field includeAvgLabel boolean
---@field showILvl boolean
---@field showUpgradeTrack boolean
---@field showGems boolean
---@field showEnchants boolean
---@field showEmbellishments boolean

---@class PGVDatabaseProfileCharacterStats
---@field showDecimals boolean
---@field decimalPlaces number
---@field lastSelectedSpecID number?
---@field customSpecStatOrders table<number, table<string, number>>

---@class PGVDatabaseProfileGeneral
---@field debug boolean
---@field showEmbellishments boolean
---@field showCharacteriLvlDecimal boolean
---@field decimalPlacesForCharacteriLvl number
---@field hideShirtTabardInfo boolean
---@field increaseCharacterInfoSize boolean
---@field minimap { hide: boolean }

---@class PGVDatabaseProfile
---@field itemLevel PGVDatabaseProfileItemLevel
---@field upgradeTrack PGVDatabaseProfileUpgradeTrack
---@field gems PGVDatabaseProfileGems
---@field enchants PGVDatabaseProfileEnchants
---@field durability PGVDatabaseProfileDurability
---@field inspect PGVDatabaseProfileInspect
---@field characterStats PGVDatabaseProfileCharacterStats
---@field general PGVDatabaseProfileGeneral

---@class PGVDatabaseDefaults: AceDB.Schema
---@field profile PGVDatabaseProfile

---@class PGVDatabase: AceDBObject-3.0
---@field profile PGVDatabaseProfile

---@class PGVTooltipDataType
---@field UpgradeTrack number
---@field Gem number
---@field Enchant number

---@class PranGearView: AceAddon, AceConsole-3.0, AceEvent-3.0
---@field db PGVDatabase
---@field categoryID number
---@field inspectHookSetup boolean
---@field inspectedUnitGUID string?
---@field noUnitTokenMessagePrinted boolean
---@field StatsCache table<string, number?>
---@field DatabaseDefaults PGVDatabaseDefaults
---@field DKEnchantAbbr DKEnchantAbbr
---@field EnchantTextReplacements TextReplacement[]
---@field ptbrEnchantTextReplacements TextReplacement[]
---@field frfrEnchantTextReplacements TextReplacement[]
---@field UpgradeTextReplacements TextReplacement[]
---@field HexColorPresets HexColorPresets
---@field GearSlots CharacterSlot[]
---@field InspectInfo InspectInfo
---@field ExpansionInfo table<string, ExpansionDetails>
---@field CurrentExpac ExpansionDetails
---@field SpecOptionKeys table<number, string>
---@field DefaultStatOrder DefaultStatOrder
---@field DefaultTankStatOrder DefaultTankStatOrder
---@field TooltipDataType PGVTooltipDataType
---@field RaceIcons RaceIcons
---@field ClassIcons ClassIcons
---@field OutlineOptions OutlineOption[]
---@field SlashOptions table
---@field SlashCmds string[]
---@field OptionsTable table
---@field PGVToggleEnchantButton PGVToggleEnchantButton
---@field ColorText fun(text: string|number, color: string): string
---@field DebugPrint fun(...)
---@field DebugTable fun(tbl: table)
---@field CompressTable fun(tbl: table)
---@field GetTableSize fun(tbl: table): number
---@field ConvertRGBToHex fun(r: number, g: number, b: number): string
---@field ConvertHexToRGB fun(hex: string): number?, number?, number?
---@field RoundNumber fun(val: number): number
---@field GetTextureString fun(texture: number|string, dim?: number): string
---@field GetTextureAtlasString fun(atlas: string, dim?: number): string
---@field CreateOptionsSpacer fun(order: number, width?: number): table
---@field IsAddOnCurrentlyRestricted fun(): boolean
---@field HandlePGVSlashCmd fun(cmd: string, input: string)
---@field OnInitialize fun(self: PranGearView)
---@field AdjustCharacterInfoWindowSize fun(self: PranGearView)
---@field HandleEquipmentOrSettingsChange fun(self: PranGearView)
---@field UpdateEquippedGearInfo fun(self: PranGearView)
---@field UpdateInspectedGearInfo fun(self: PranGearView, unitGUID: string, forceUpdate?: boolean)
---@field IsItemEquippedInSlot fun(self: PranGearView, slot: ItemSlot, isInspect?: boolean): boolean, ItemMixin|table
---@field IsSocketableSlot fun(self: PranGearView, slot: ItemSlot): boolean
---@field IsAuxSocketableSlot fun(self: PranGearView, slot: ItemSlot): boolean
---@field IsEnchantableSlot fun(self: PranGearView, slot: ItemSlot): boolean
---@field AbbreviateText fun(self: PranGearView, text: string, replacementTable: TextReplacement[]): string
---@field GetLegacyEnchantTextureID fun(self: PranGearView, enchantTextAbbr: string): number
---@field IsTimerunningCharacter fun(self: PranGearView): boolean
---@field AreUpgradeTracksShownForCharacter fun(self: PranGearView): boolean
---@field AreGemsShownForCharacter fun(self: PranGearView): boolean
---@field AreEnchantsShownForCharacter fun(self: PranGearView): boolean
---@field AreEmbellishmentsShownForCharacter fun(self: PranGearView): boolean
---@field GetStatOrderValuesHandler fun(self: PranGearView): number[]
---@field GetStatOrderHandler fun(self: PranGearView, item: string|table): number
---@field SetStatOrderHandler fun(self: PranGearView, item: string|table, val: any)
---@field GetCharacterCurrentSpecIDAndRole fun(self: PranGearView): number?, string?
---@field InitializeCustomSpecStatOrderDB fun(self: PranGearView, selectedSpecID?: number, reset?: boolean)
---@field GetSpecAndRoleForSelectedCharacterStatsOption fun(self: PranGearView): number?, string?
---@field CachePlayerStatValues fun(self: PranGearView)
---@field ReorderStatFramesBySpec fun(self: PranGearView)
---@field ShowDecimalStatValues fun(self: PranGearView)
---@field BuildCreditsGroup fun(self: PranGearView): table
