local L = LibStub("AceLocale-3.0"):NewLocale("PranGearView", "enUS", true)

if not L then return end

------------ Options ------------
L["usage_desc"] = "Choose which information you would like shown for equipped items in the Character Info window"
L["Item Level"] = "Item Level"
L["show_ilvl_desc"] = "Display item levels for equipped items"
L["Gems"] = "Gems"
L["show_gems_desc"] = "Display socketed gems for equipped items"
L["Enchants"] = "Enchants"
L["show_enchants_desc"] = "Display enchants for equipped items"
L["Durability"] = "Durability"
L["show_durability_desc"] = "Display durability percentage for equipped items"
L["Reset"] = "Reset"
L["Font Scale"] = "Font Scale"
L["ilvl_font_scale_desc"] = "Change the size of item level text relative to default text size"
L["ench_font_scale_desc"] = "Change the size of enchant text relative to default text size"
L["dur_font_scale_desc"] = "Change the size of item durability percentage relative to default text size"
L["Show Upgrade Track"] = "Show Upgrade Track"
L["upgrade_track_desc"] = "Display the item's upgrade track and progress next to the item level"
L["ilvl_color_opts_desc"] = "When none of the color options below are selected, all item levels are shown in white"
L["Use Item Quality Color"] = "Use Item Quality Color"
L["Use Class Color"] = "Use Class Color"
L["Use Custom Color"] = "Use Custom Color"
L["ilvl_use_quality_color_desc"] = "Changes the color of item levels according to an item's quality"
L["ilvl_use_class_color_desc"] = "Changes the color of item levels to the character's class color"
L["ilvl_use_custom_color_desc"] = "Customizes the color of item levels"
L["custom_color_desc"] = "You may choose a custom color from the color picker or enter the hex code for a specific color."
L["custom_color_instruction"] = "Color codes should be entered in the format #|cFFff3300RR|cFF1eff00GG|cFF0070ddBB|r"
L["Choose a Color"] = "Choose a Color"
L["Icon Scale"] = "Icon Scale"
L["gem_icon_scale_desc"] = "Change the size of gem icons relative to the default size"
L["Missing Gems Indicator"] = "Missing Gems Indicator"
L["missing_gems_desc"] = "Indicates when an item that can be socketed isn't"
L["add_socket_desc"] = "|A:Socket-Prismatic-Closed:20:20:0:5|a indicates that a socket can be added to an item"
L["empty_socket_desc"] = "|T458977:20:20:0:5|t indicates an empty socket on an item"
L["Only Show Missing Gems for Max Level"] = "Only Show Missing Gems for Max Level"
L["missing_gems_max_lvl_desc"] = "Only show missing gems for items that can be socketed when a character is at max level"
L["Missing Enchant Indicator"] = "Missing Enchant Indicator"
L["missing_ench_desc"] = "Indicates when an item that can be enchanted isn't with a |T523826:10:10|t symbol"
L["Enchant"] = "Enchant"
L["no_enchant_text"] = "-Ench"
L["Only Show Missing Enchants for Max Level"] = "Only Show Missing Enchants for Max Level"
L["missing_ench_max_lvl_desc"] = "Only show missing enchant text for items that can be enchanted when a character is at max level"
L["ench_color_opts_desc"] = "|cFFffd100Enchant quality symbol will not be affected by the |cFFffffffUse Custom Color |cFFffd100option for enchant text|r"
L["ench_use_custom_color_desc"] = "Customizes the color of enchant text"
L["dur_hidden_at_100"] = "Durability will always be hidden if it is 100%"
L["Character Stats"] = "Character Stats"
L["Specialization"] = "Specialization"
L["custom_spec_desc"] = "Customize the secondary & teritary stat order for each spec in the Character Info window"
L["Secondary Stats"] = "Secondary Stats"
L["Tertiary Stats"] = "Tertiary Stats"
L["Tank-Specific Stats"] = "Tank-Specific Stats"
L["Other Options"] = "Other Options"
L["Alternate Item Level Placement"] = "Alternate Item Level Placement"
L["ilvl_unchecked_info_text"] = "|cFFffd100Does nothing if the |cFFffffffItem Level |cFFffd100checkbox is unchecked|r"
L["alt_ilvl_placement_desc"] = "Displays the item level on top of the equipment icon instead of next to it"
L["Show Embellishments"] = "Show Embellishments"
L["show_embellish_desc"] = "Indicate equipped embellished gear with a small green star"
L["Hide Shirt & Tabard Info"] = "Hide Shirt & Tabard Info"
L["hide_shirt_tabard_desc"] = "Hides information about the equipped shirt and tabard when checked"
L["Debug Mode"] = "Debug Mode"
L["debug_mode_desc"] = "Display debugging messages in the default chat window"
L["dont_enable_warning"] = "You should never need to enable this"

------------ Slash Commands ------------
L["config_desc"] = "Open the AddOn options window"
L["ilvl_desc"] = "Toggle showing item level"
L["gems_desc"] = "Toggle showing socketed gems"
L["ench_desc"] = "Toggle showing enchants"
L["dur_desc"] = "Toggle showing durability percentages"
L["etext_desc"] = "Toggle showing enchant text"
L["debug_desc"] = "Toggle displaying debug messages"

------------ UI Elements ------------
L["Show Enchant Text"] = "Show Enchant Text"
L["Hide Enchant Text"] = "Hide Enchant Text"

L["invalid_hex_code_msg"] = "Invalid hexadecimal color code provided."
