local L = LibStub("AceLocale-3.0"):NewLocale("PranGearView", "enUS", true, true)

if not L then return end

------------ Options ------------
L["Item Level"] = "Item Level"
L["Upgrade Track"] = "Upgrade Track"
L["Gems"] = "Gems"
L["Enchants"] = "Enchants"
L["Durability"] = "Durability"
L["Embellishments"] = "Embellishments"
L["Reset"] = "Reset"
L["Font Scale"] = "Font Scale"
L["Outline"] = "Outline"
L["Use Item Quality Color"] = "Use Item Quality Color"
L["Use Class Color"] = "Use Class Color"
L["Use S&L Colors"] = "Use S&L Colors"
L["Use Custom Color"] = "Use Custom Color"
L["Choose a Color"] = "Choose a Color"
L["Icon Scale"] = "Icon Scale"
L["Show Missing Gems & Sockets"] = "Show Missing Gems & Sockets"
L["Only Show for Max Level"] = "Only Show for Max Level"
L["Missing Enchant Indicator"] = "Missing Enchant Indicator"
L["Inspect Window"] = "Inspect Window"
L["Show Gear Info on Inspect"] = "Show Gear Info on Inspect"
L["Character Stats"] = "Character Stats"
L["Specialization"] = "Specialization"
L["Secondary Stats"] = "Secondary Stats"
L["Tertiary Stats"] = "Tertiary Stats"
L["Tank Stats"] = "Tank Stats"
L["Other Options"] = "Other Options"
L["Alternate Item Level Placement"] = "Alternate Item Level Placement"
L["Show Embellishments"] = "Show Embellishments"
L["Hide Shirt & Tabard Info"] = "Hide Shirt & Tabard Info"
L["Debug Mode"] = "Debug Mode"

L["Choose information to show in the Character Info window"] = "Choose information to show in the Character Info window"
L["Display item levels for equipped items"] = "Display item levels for equipped items"
L["Display upgrade track and progress"] = "Display upgrade track and progress"
L["Display gem and socket information for equipped items"] = "Display gem and socket information for equipped items"
L["Display enchant information for equipped items"] = "Display enchant information for equipped items"
L["Display durability percentages for equipped items"] = "Display durability percentages for equipped items"
L["Scale item level text size relative to the default"] = "Scale item level text size relative to the default"
L["The outline style to add to item level text"] = "The outline style to add to item level text"
L["Does nothing if the Alternate Item Level Placement checkbox is checked"] = "|cFFFFD100Does nothing if the |cFFFFFFFFAlternate Item Level Placement |cFFFFD100checkbox is checked|r"
L["Scale upgrade track text size relative to the default"] = "Scale upgrade track text size relative to the default"
L["The outline style to add to upgrade track text"] = "The outline style to add to upgrade track text"
L["Scale gem icon size relative to the default"] = "Scale gem icon size relative to the default"
L["Scale enchant text size relative to the default"] = "Scale enchant text size relative to the default"
L["The outline style to add to enchant text"] = "The outline style to add to enchant text"
L["Scale durability text size relative to the default"] = "Scale durability text size relative to the default"
L["Item levels shown in white when no color options are selected"] = "Item levels shown in white when no color options are selected"
L["Color item levels based on item quality"] = "Color item levels based on item quality"
L["Color item levels based on the character's class"] = "Color item levels based on the character's class"
L["Color highest item level in green, lowest item level in red, and the rest in orange."] = "Color highest item level in |cFF1EFF00green|r, lowest item level in |cFFC41E3Ared|r, and the rest in |cFFFF7C0Aorange|r."
L["This color scheme follows a similar pattern to the Shadow & Light plugin for ElvUI"] = "This color scheme follows a similar pattern to the |cFFFFD100Shadow & Light|r plugin for |cFFFFD100ElvUI|r"
L["Customize item level color"] = "Customize item level color"
L["Customize upgrade track color for current season items"] = "Customize upgrade track color for current season items"
L["Choose from the color picker or enter the hex code for a specific color."] = "Choose from the color picker or enter the hex code for a specific color."
L["Color codes should be entered in the format #RRGGBB"] = "Color codes should be entered in the format #|cFFff3300RR|cFF1eff00GG|cFF0070ddBB|r"
L["Show when an item is missing gems or sockets"] = "Show when an item is missing gems or sockets"
L["Hide missing gem & socket info for characters under the level cap"] = "Hide missing gem & socket info for characters under the level cap"
L["indicates that a socket can be added to the item"] = "|A:Socket-Prismatic-Closed:20:20:0:5|a indicates that a socket can be added to the item"
L["indicates an empty socket on the item"] = "|T458977:20:20:0:5|t indicates an empty socket on the item"
L["Show when an item is missing an enchant with a warning symbol"] = "Show when an item is missing an enchant with a |T523826:10:10|t symbol"
L["Enchant"] = "Enchant"
L["Hide missing enchant info for characters under the level cap"] = "Hide missing enchant info for characters under the level cap"
L["Enchant quality symbol is not affected by the custom color option"] = "Enchant quality symbol is not affected by the custom color option"
L["Customize enchant text color"] = "Customize enchant text color"
L["Durability always hidden at 100%"] = "Durability always hidden at 100%"
L["Displays information about equipped gear when inspecting another player in your party or raid"] = "Displays information about equipped gear when inspecting another player in your party or raid"
L["Choose which information should be displayed when inspecting another player."] = "Choose which information should be displayed when inspecting another player."
L["Colors, size, and other display settings when inspecting a character will follow the same settings as the Character Info window."] = "Colors, size, and other display settings when inspecting a character will follow the same settings as the Character Info window."
L["Customize secondary & tertiary stat order in the Character Info window by specialization"] = "Customize secondary & tertiary stat order in the Character Info window by specialization"
L["Display item levels on top of equipment icons"] = "Display item levels on top of equipment icons"
L["Does nothing if the Item Level checkbox is unchecked"] = "|cFFffd100Does nothing if the |cFFffffffItem Level |cFFffd100checkbox is unchecked|r"
L["Show a green star in the top-left corner of embellished equipment"] = "Show a green star in the top-left corner of embellished equipment"
L["Hide information for equipped shirt & tabard"] = "Hide information for equipped shirt & tabard"
L["Display debugging messages in the default chat window"] = "Display debugging messages in the default chat window"
L["You should never need to enable this"] = "You should never need to enable this"

------------ Slash Commands ------------
L["Open the AddOn options window"] = "Open the AddOn options window"
L["Toggle showing item level"] = "Toggle showing item level"
L["Toggle showing upgrade track"] = "Toggle showing upgrade track"
L["Toggle showing gem info"] = "Toggle showing gem info"
L["Toggle showing enchant info"] = "Toggle showing enchant info"
L["Toggle showing durability percentages"] = "Toggle showing durability percentages"
L["Toggle showing enchant text in the Character Info window"] = "Toggle showing enchant text in the Character Info window"
L["Toggle showing gear info when inspecting another player in your party or raid"] = "Toggle showing gear info when inspecting another player in your party or raid"

------------ UI Elements ------------
L["Show Enchant Text"] = "Show Enchant Text"
L["Hide Enchant Text"] = "Hide Enchant Text"
L["Invalid hexadecimal color code provided."] = "Invalid hexadecimal color code provided."

------------ Credits ------------
L["Credits"] = "Credits"
L["Contributors"] = "Contributors"
L["If you would like to contribute to development, you can find the repository on GitHub."] = "If you would like to contribute to development, you can find the repository on |cFF1eff00GitHub|r."
L["Please follow the development guidelines outlined in the README document."] = "Please follow the development guidelines outlined in the README document."
L["Special Thanks"] = "Special Thanks"
L["Connect"] = "Connect"
