local L = LibStub("AceLocale-3.0"):NewLocale("PranGearView", "ptBR")

if not L then return end

------------ Options ------------
L["Item Level"] = "Nivel do item"
L["Upgrade Track"] = "Linha de evolução"
L["Gems"] = "Gemas"
L["Enchants"] = "Encantamentos"
L["Durability"] = "Durabilidade"
L["Reset"] = "Resetar"
L["Font Scale"] = "Tamanho da fonte"
L["Use Item Quality Color"] = "Usar a cor de qualidade do item"
L["Use Class Color"] = "Usar cor de classe"
L["Use Custom Color"] = "Usar cor customizada"
L["Choose a Color"] = "Escolha uma cor"
L["Icon Scale"] = "Tamanho do icone"
L["Show Missing Gems & Sockets"] = "Mostrar gemas e soquetes faltantes"
L["Only Show for Max Level"] = "Mostrar somente para nível máximo"
L["Missing Enchant Indicator"] = "Indicador de encantamento faltanteMissing Enchant Indicator"
L["Inspect Window"] = "Janela de Inspeção"
L["Show Gear Info on Inspect"] = "Mostrar Informação de Equipamento ao Inspecionar"
L["Character Stats"] = "Atributos do personagem"
L["Specialization"] = "Especialização"
L["Secondary Stats"] = "Atributo secundário"
L["Tertiary Stats"] = "Atributo terciário"
L["Tank Stats"] = "Atributo do tanque"
L["Other Options"] = "Outras opções"
L["Alternate Item Level Placement"] = "Alterar local do nível do item"
L["Show Embellishments"] = "Mostrar embelezamentos"
L["Hide Shirt & Tabard Info"] = "Esconder informações de camisa & tabardo"
L["Debug Mode"] = "Modo de depuração"

L["Choose information to show in the Character Info window"] = "Escolha a informação para mostrar na janela de informação do personagem"
L["Display item levels for equipped items"] = "Mostrar nível do item para itens equipados"
L["Display upgrade track and progress"] = "Mostrar linha de evolução e progresso"
L["Display gem and socket information for equipped items"] = "Mostrar informações de gemas e soquetes para itens equipados"
L["Display enchant information for equipped items"] = "Mostrar informação de encantamento para itens equipados"
L["Display durability percentages for equipped items"] = "Mostrar porcentagem de durabilidade para itens equipados"
L["Scale item level text size relative to the default"] = "Alterar o tamanho do texto do nível relativo ao padrão"
L["Scale upgrade track text size relative to the default"] = "Alterar o tamanho do linha de evolução relativo ao padrão"
L["Scale gem icon size relative to the default"] = "Alterar o tamanho do icone da gema relativo ao padrão"
L["Scale enchant text size relative to the default"] = "Alterar o tamanho do texto do encantamento relativo ao padrão"
L["Scale durability text size relative to the default"] = "Alterar o tamanho do texto da durabilidade relativo ao padrão"
L["Item levels shown in white when no color options are selected"] = "Nivel dos itens mostrado em branco quando nenhuma opção de cor for selecionada"
L["Color item levels based on item quality"] = "Nivel da cor do item baseado na qualidade do item"
L["Color item levels based on the character's class"] = "Nivel da cor do item baseado na classe do personagem"
L["Customize item level color"] = "Customizar a cor do nível do item"
L["Customize upgrade track color for current season items"] = "Customizar a cor do linha de evolução"
L["Choose from the color picker or enter the hex code for a specific color."] = "Escolha da paleta de cores ou entre com o código HEX(hexadecimal) para uma cor especifica."
L["Color codes should be entered in the format #RRGGBB"] = "Códigos de cores devem ser colocados no formato #|cFFff3300RR|cFF1eff00GG|cFF0070ddBB|r (Vermelho, vermelho, verde, verde, azul e azul)"
L["Show when an item is missing gems or sockets"] = "Mostrar quando um item estiver faltando gemas ou soquetes"
L["Hide missing gem & socket info for characters under the level cap"] = "Esconder informação de gemas & soquetes para personagens abaixo do nível selecionado"
L["indicates that a socket can be added to the item"] = "|A:Socket-Prismatic-Closed:20:20:0:5|a indica que um soquete pode ser adicionado ao item"
L["indicates an empty socket on the item"] = "|T458977:20:20:0:5|t indica um soquete vazio no item"
L["Show when an item is missing an enchant with a warning symbol"] = "Mostra quando um item esta faltando um encantamento com um |T523826:10:10|t símbolo"
L["Enchant"] = "Encantamento"
L["Hide missing enchant info for characters under the level cap"] = "Esconder informação de encantamento faltante para personagens abaixo do nível selecionado"
L["Enchant quality symbol is not affected by the custom color option"] = "Símbolo de qualidade de encantamento não é afetado pela opção de cor customizada"
L["Customize enchant text color"] = "Customiza a cor do texto de encantamento"
L["Durability always hidden at 100%"] = "Durabilidade sempre escondida com 100%"
L["Displays information about equipped gear when inspecting another player in your party or raid"] = "Mostrar informação sobre equipamento equipado quando inspecionar outro jogador no seu grupo ou raide"
L["Choose which information should be displayed when inspecting another player."] = "Escolha qual informação será mostrada quando inspecionar outro jogador."
L["Colors, size, and other display settings when inspecting a character will follow the same settings as the Character Info window."] = "Cores, tamanhos e outras configurações de display quando inspecionando um personagem seguirão as mesmas configurações de uma janela de informação de personagem."
L["Customize secondary & tertiary stat order in the Character Info window by specialization"] = "Customiza a ordem de atributos secundário e terciário na janela de informação do personagem por especialização"
L["Display item levels on top of equipment icons"] = "Mostre o nível dos itens no topo do icone de equipamento"
L["Does nothing if the Item Level checkbox is unchecked"] = "|cFFffd100Não faz nada se a caixa de seleção do |cFFffffffNível do item |cFFffd100 estiver desmarcada|r"
L["Show a green star in the top-left corner of embellished equipment"] = "Mostre uma estrela verde no canto de cima a esquerda do equipamento embelezado"
L["Hide information for equipped shirt & tabard"] = "Esconda informações para camisa e tabardo equipado"
L["Display debugging messages in the default chat window"] = "Mostre as mensagens de depuração na janela de bate papo padrão"
L["You should never need to enable this"] = "Voce nunca deve precisar ativar isso"

------------ Slash Commands ------------
L["Open the AddOn options window"] = "Abrir a janela de opções de AddOn"
L["Toggle showing item level info"] = "Alterar a exibição de informação do nível do item"
L["Toggle showing gem info"] = "Alterar a exibição de informação da gema"
L["Toggle showing enchant info"] = "Alterar a exibição de informação do encantamento"
L["Toggle showing durability percentages"] = "Alterar a exibição de informação de porcentagens de durabilidade"
L["Toggle showing enchant text in the Character Info window"] = "Alterar a exibição de texto de encantamento na janela de informação de personagem"
L["Toggle showing gear info when inspecting another player in your party or raid"] = "Trocar a exibição de informação de equipamento quando inspecionando outro jogador no seu grupo ou raide"

------------ UI Elements ------------
L["Show Enchant Text"] = "Mostrar texto de encantamento"
L["Hide Enchant Text"] = "Esconder texto de encantamento"
L["Invalid hexadecimal color code provided."] = "Código de cor hexadecimal fornecida invalida."

------------ Credits ------------
L["Credits"] = "Creditos"
L["Contributors"] = "Contribuidores"
L["If you would like to contribute to development, you can find the repository on GitHub."] = "Se voce gostaria de contribuir para o desenvolvimento, voce pode achar o repositório no |cFF1eff00GitHub|r."
L["Please follow the development guidelines outlined in the README document."] = "Por favor siga as diretrizes de desenvolvimento marcadas no documento README."
L["Special Thanks"] = "Obrigados especias"
L["Connect"] = "Conectar"
