-- Localization provided by ZamestoTV
local L = LibStub("AceLocale-3.0"):NewLocale("PranGearView", "ruRU")

if not L then return end
-- Первод ZamestoTV
------------ Options ------------
L["Item Level"] = "Уровень предмета"
L["Upgrade Track"] = "Путь улучшения"
L["Gems"] = "Самоцветы"
L["Enchants"] = "Чары"
L["Durability"] = "Прочность"
L["Embellishments"] = "Украшения"
L["Reset"] = "Сброс"
L["Font Scale"] = "Масштаб шрифта"
L["Outline"] = "Обрисовывать"
L["Use Item Quality Color"] = "Использовать цвет качества предмета"
L["Use Class Color"] = "Использовать цвет класса"
L["Use Item Level Gradient"] = "Используйте уровень предмета градиент"
L["Use Custom Color"] = "Использовать свой цвет"
L["Choose a Color"] = "Выбрать цвет"
L["Icon Scale"] = "Масштаб значков"
L["Show Missing Gems & Sockets"] = "Показывать отсутствующие самоцветы и гнезда"
L["Only Show for Max Level"] = "Показывать только для максимального уровня"
L["Missing Enchant Indicator"] = "Индикатор отсутствующих чар"
L["Inspect Window"] = "Окно осмотра"
L["Average Item Level"] = "Средний уровень предмета"
L["Include \"Avg\" Label"] = "Включить метку «Средн»"
L["Show Gear Info on Inspect"] = "Показать информацию о снаряжении при осмотре"
L["Character Stats"] = "Характеристики персонажа"
L["Specialization"] = "Специализация"
L["Secondary Stats"] = "Вторичные характеристики"
L["Tertiary Stats"] = "Третичные характеристики"
L["Tank Stats"] = "Характеристики танка"
L["Other Options"] = "Другие настройки"
L["Show Minimap Icon"] = "Показать значок миникарты"
L["Alternate Item Level Placement"] = "Альтернативное размещение уровня предмета"
L["Show Embellishments"] = "Показывать украшения"
L["Hide Shirt & Tabard Info"] = "Скрыть информацию о рубашке и накидке"
L["Debug Mode"] = "Режим отладки"

L["Choose information to show in the Character Info window"] = "Выберите информацию для отображения в окне информации о персонаже"
L["Display item levels for equipped items"] = "Отображать уровни предметов для экипированных предметов"
L["Display upgrade track and progress for equipped items"] = "Отображать путь улучшения и прогресс для экипированных предметов"
L["Display gem and socket information for equipped items"] = "Отображать информацию о самоцветах и гнездах для экипированных предметов"
L["Display enchant information for equipped items"] = "Отображать информацию о чарах для экипированных предметов"
L["Display durability percentages for equipped items"] = "Отображать проценты прочности для экипированных предметов"
L["Scale item level text size relative to the default"] = "Масштабировать размер текста уровня предмета относительно стандартного"
L["The outline style to add to item level text"] = "Стиль контура, добавляемый к тексту для уровни предметов"
L["Does nothing if the Alternate Item Level Placement checkbox is checked"] = "|cFFFFD100Не действует, если флажок |cFFFFFFFFАльтернативное размещение уровня предмета |cFFFFD100нустановлен|r"
L["Scale upgrade track text size relative to the default"] = "Масштабировать размер текста путь улучшения относительно стандартного"
L["The outline style to add to upgrade track text"] = "Стиль контура, добавляемый к тексту для путь улучшения"
L["Scale gem icon size relative to the default"] = "Масштабировать размер значков самоцветов относительно стандартного"
L["Scale enchant text size relative to the default"] = "Масштабировать размер текста чар относительно стандартного"
L["The outline style to add to enchant text"] = "Стиль контура, добавляемый к тексту для чары"
L["Scale durability text size relative to the default"] = "Масштабировать размер текста прочности относительно стандартного"
L["Item levels shown in white when no color options are selected"] = "Уровни предметов отображаются белым, если не выбраны цветовые настройки"
L["Color item levels based on item quality"] = "Окрашивать уровни предметов в зависимости от качества предмета"
L["Color item levels based on the character's class"] = "Окрашивать уровни предметов в зависимости от класса персонажа"
L["Color highest item level in green, lowest item level in red, and the rest in yellow."] = "Раскрасьте самый высокий уровень предмета |cFF1EFF00зеленый|r цветом, самый низкий уровень предмета — |cFFFF3300красный|r, а все остальное — |cFFFFF468желтый|r."
L["This color scheme follows a similar pattern to the Shadow & Light plugin for ElvUI"] = "Эта цветовая схема следует шаблону, похожему на плагин |cFFFFD100Shadow & Light|r для |cFFFFD100ElvUI|r"
L["Customize item level color"] = "Настроить цвет уровня предмета"
L["Customize upgrade track color for current season items"] = "Настроить цвет путь улучшения предмета для предметов текущего сезона"
L["Choose from the color picker or enter the hex code for a specific color."] = "Выберите цвет из палитры или введите шестнадцатеричный код для конкретного цвета."
L["Color codes should be entered in the format #RRGGBB"] = "Цветовые коды должны вводиться в формате #|cFFff3300RR|cFF1eff00GG|cFF0070ddBB|r (красный, красный, зеленый, зеленый, синий, и синий)"
L["Show when an item is missing gems or sockets"] = "Показывать, если у предмета отсутствуют самоцветы или гнезда"
L["Hide missing gem & socket info for characters under the level cap"] = "Скрывать информацию об отсутствующих самоцветах и гнездах для персонажей ниже максимального уровня"
L["indicates that a socket can be added to the item"] = "|A:Socket-Prismatic-Closed:20:20:0:5|a указывает, что к предмету можно добавить гнездо"
L["indicates an empty socket on the item"] = "|T458977:20:20:0:5|t указывает на пустое гнездо на предмете"
L["Show when an item is missing an enchant with a warning symbol"] = "Показывать, если у предмета отсутствуют чары, с символом предупреждения |T523826:10:10|t"
L["Enchant"] = "Чары"
L["Hide missing enchant info for characters under the level cap"] = "Скрывать информацию об отсутствующих чарах для персонажей ниже максимального уровня"
L["Enchant quality symbol is not affected by the custom color option"] = "Символ качества чар не зависит от настройки собственного цвета"
L["Customize enchant text color"] = "Настроить цвет текста чар"
L["Durability text is always hidden at 100%"] = "Прочность всегда скрыта при 100%"
L["Displays information about equipped gear when inspecting another player"] = "Отображает информацию об экипированном снаряжении при осмотре другого игрока"
L["Choose which information should be displayed when inspecting another player."] = "Выберите, какая информация должна отображаться при проверке другого игрока."
L["Colors, size, and other display settings when inspecting a character will follow the same settings as the Character Info window."] = "Цвета, размер и другие параметры отображения при просмотре персонажа будут соответствовать тем же настройкам, что и в окне «Информация о персонаже»."
L["Display average item level in the character's class color"] = "Отображать средний уровень предмета в цвет класса персонажа"
L["Adds the text \"Avg: \" before the average item level."] = "Добавляет текст |cFFFFD100«Средн: »|r перед средний уровень предмета."
L["This can help easily identify the average item level when there is a lot of information shown in the Inspect window."] = "Это может помочь легко идентифицировать средний уровень предмета, когда на окно осмотра отображается много информации."
L["Avg"] = "Средн"
L["Customize secondary & tertiary stat order in the Character Info window by specialization"] = "Настроить порядок вторичных и третичных характеристик в окне информации о персонаже по специализации"
L["Display item levels on top of equipment icons"] = "Отображать уровни предметов поверх значков экипировки"
L["Show an icon on the minimap to open the AddOn settings"] = "Показывать значок на мини-карте, чтобы открыть окно настроек аддона"
L["Show a green star in the top-left corner of embellished equipment"] = "Показывать зеленую звезду в верхнем левом углу украшенной экипировки"
L["Hide information for equipped shirt & tabard"] = "Скрывать информацию о надетых рубашке и накидке"
L["Display debugging messages in the default chat window"] = "Отображать отладочные сообщения в окне чата по умолчанию"
L["You should never need to enable this"] = "Вам никогда не придется включать эту опцию"

------------ Slash Commands ------------
L["Open the AddOn options window"] = "Открыть окно настроек аддона"
L["Toggle showing item level"] = "Переключить отображение уровне предмета"
L["Toggle showing upgrade track"] = "Переключить отображение путь улучшения"
L["Toggle showing gem info"] = "Переключить отображение информации о самоцветах"
L["Toggle showing enchant info"] = "Переключить отображение информации о чарах"
L["Toggle showing durability percentages"] = "Переключить отображение процентов прочности"
L["Toggle showing enchant text in the Character Info window"] = "Переключить отображение текста чар в окне информации о персонаже"
L["Toggle showing gear info when inspecting another player"] = "Включить/выключить отображение информации о экипировке при осмотре другого игрока"
L["Show/hide the minimap icon"] = "Показать/скрыть значок миникарты"

------------ UI Elements ------------
L["Show Enchant Text"] = "Показать текст чар"
L["Hide Enchant Text"] = "Скрыть текст чар"
L["Invalid hexadecimal color code provided."] = "Указан неверный шестнадцатеричный код цвета."

------------ Credits ------------
L["Credits"] = "Благодарности"
L["Contributors"] = "Участники"
L["If you would like to contribute to development, you can find the repository on GitHub."] = "Если вы хотите внести вклад в разработку, вы можете найти репозиторий на |cFF1eff00GitHub|r."
L["Please follow the development guidelines outlined in the README document."] = "Пожалуйста, следуйте рекомендациям по разработке, описанным в документе README."
L["Special Thanks"] = "Особая благодарность"
L["Connect"] = "Связаться"
